before_install:
  - sudo add-apt-repository ppa:mbudde/ledger -y
  - sudo apt-get update
  - sudo apt-get install ledger -y

language: node_js
node_js:
  - "9.11.1"

script:
  - npm run express &
  - npm run test