before_install:
  - sudo add-apt-repository ppa:mbudde/ledger
  - sudo apt-get update
  - sudo apt-get install -y ledger

language: node_js
node_js:
  - "9.11.1"

script:
  - npm run express &
  - npm run test